Updated rebecca to work with boost_1_55_0, xerces3.1, g++-4.6.3 with autoconf under Ubuntu 12.04

diff --git a/ext/RebeccaAIML-src-9871/build_files/autoconf/lib/configure b/ext/RebeccaAIML-src-9871/build_files/autoconf/lib/configure
--- a/ext/RebeccaAIML-src-9871/build_files/autoconf/lib/configure
+++ b/ext/RebeccaAIML-src-9871/build_files/autoconf/lib/configure
@@ -22387,6 +22387,87 @@ fi
 
 
 
+echo "$as_me:$LINENO: checking for main in -lboost_system" >&5
+echo $ECHO_N "checking for main in -lboost_system... $ECHO_C" >&6
+if test "${ac_cv_lib_boost_system_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lboost_system  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_boost_system_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_boost_system_main=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_boost_system_main" >&5
+echo "${ECHO_T}$ac_cv_lib_boost_system_main" >&6
+if test $ac_cv_lib_boost_system_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBBOOST_SYSTEM 1
+_ACEOF
+
+  LIBS="-lboost_system $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error:
+RebeccaAIML requires
+boost system to be installed to work.  Download Boost
+at http://www.boost.org/
+" >&5
+echo "$as_me: error:
+RebeccaAIML requires
+boost system to be installed to work.  Download Boost
+at http://www.boost.org/
+" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+
 echo "$as_me:$LINENO: checking for main in -lboost_regex" >&5
 echo $ECHO_N "checking for main in -lboost_regex... $ECHO_C" >&6
 if test "${ac_cv_lib_boost_regex_main+set}" = set; then
